// Code generated by goctl. DO NOT EDIT.
package types

type AccountReply struct {
	Account  string `json:"account"`
	NickName string `json:"nick_name"`
	JwtToken
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
}

type LoginRequest struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type AccountInfoResponse struct {
	AccountReply
}

type LoginResponse struct {
	AccountReply
}

type RegisterRequest struct {
	Account  string `json:"account"`
	Mobile   string `json:"mobile"`
	NickName string `json:"nick_name"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	AccountReply
}
