// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	account "github.com/portgas-x/saas-platform/service/account/cmd/api/internal/handler/account"
	"github.com/portgas-x/saas-platform/service/account/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/login",
				Handler: account.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/account/register",
				Handler: account.RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Jwt, serverCtx.Casbin},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/account/accountinfo",
					Handler: account.AccountinfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/account/refresh",
					Handler: account.RefreshTokenHandler(serverCtx),
				},
			}...,
		),
	)
}
