// Code generated by goctl. DO NOT EDIT!
// Source: account.proto

package server

import (
	"context"

	"github.com/portgas-x/saas-platform/service/account/cmd/rpc/account"
	"github.com/portgas-x/saas-platform/service/account/cmd/rpc/internal/logic"
	"github.com/portgas-x/saas-platform/service/account/cmd/rpc/internal/svc"
)

type AccountServer struct {
	svcCtx *svc.ServiceContext
}

func NewAccountServer(svcCtx *svc.ServiceContext) *AccountServer {
	return &AccountServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountServer) Login(ctx context.Context, in *account.LoginRequest) (*account.Response, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *AccountServer) Register(ctx context.Context, in *account.RegisterRequest) (*account.Response, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *AccountServer) GetAccount(ctx context.Context, in *account.GetAccountRequest) (*account.GetAccountResponse, error) {
	l := logic.NewGetAccountLogic(ctx, s.svcCtx)
	return l.GetAccount(in)
}

func (s *AccountServer) CreateAccount(ctx context.Context, in *account.CreateAccountRequest) (*account.CreateAccountResponse, error) {
	l := logic.NewCreateAccountLogic(ctx, s.svcCtx)
	return l.CreateAccount(in)
}
